### ISSUE TITLE
How to add this kernel into embedded project with using meta-adi ?

### ISSUE THREAD

**Issue by esraltun** [samiemostafavi/adrv9361-linux#1]
Hi,
I m working on srslte. I'm using soapyplutosdr and iio driver for running on ad9361 trancelver. I tried to use your modified kernel. For adding this kernel, I use Petalinux tool. Normally I can create a kernel image using Linux kernel that lncluded ADI drlvers via meta-adi.
I tried to modified meta-adi files but I didn't add adrv9361-linux kernel.
How can I solve this problem?
Thanks.

**Comment by samiemostafavi** [comment]
Hi,

This project is still ongoing. Probably I had to make the repository private.
The point is that FPGA hdl design should also be altered in order to make it work. In addition to that we have a new driver instead of soapyplutosdr.
I will release the project soon so keep in touch!

Best,
Samie
